name: Disk Usage Monitor Automation

on:
        push:
                paths:
                        - 'DiskUsageMonitor/**'
                        - 'github/workflows/**'
                workflow_dispatch:
                        inputs:
                        threshold:
                                required: true
                                default: '80'

jobs:
        run-script:
                runs-on: ubuntu-latest

                steps:
                - name: Checkout repository
                  uses: actions/checkout@v4

                - name: Run Disk Usage Monitor Script
                  run: |
                        cd DiskUsageMonitor 
                        chmod +x DiskUsageMonitor.sh
                        ./DiskUsageMonitor.sh ${{ github.event.inputs.threshold }}
