# ResourceMonitor/.github/workflows/resource_monitor.yml

name: Resource Monitor Automation

on:
  push:
    paths:
      - 'ResourceMonitor/**'
      - 'github/workflows/**'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: self-hosted 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Resource Monitor Script
      run: |
              whoami
              pwd
              cd ResourceMonitor
              chmod +x ResourceMonitor.sh
              ./ResourceMonitor.sh
